#!/bin/bash

source_file="a"
destinations=("2-groups" "3-new_owner" "4-empty" "5-execute" "6-multiple_permissions" "7-everybody" "8-James_Bond" "9-John_Doe" "10-mirror_permissions" "11-directories_permissions" "12-directory_permissions" "13-change_group")
advanced=("100-change_owner_and_group" "101-symbolic_link_permissions" "102-if_only" "103-Star_Wars")

redirection=("0-hello_world"
       "1-confused_smiley"
"2-hellofile"
"3-twofiles"
"4-lastlines"
"5-firstlines"
"6-third_line"
"7-file"
"8-cwd_state"
"9-duplicate_last_line"
"10-no_more_js"
"11-directories"
"12-newest_files"
"13-unique"
"14-findthatword"
"15-countthatword"
"16-whatsnext"
"17-hidethisword"
"18-letteronly"
"19-AZ"
"20-hiago"
"21-reverse"
"22-users_and_homes")

for dest in "${redirection[@]}"; do
  cp "$source_file" "$dest"
done
