#!/bin/bash

source_file="a"
destinations=("2-groups" "3-new_owner" "4-empty" "5-execute" "6-multiple_permissions" "7-everybody" "8-James_Bond" "9-John_Doe" "10-mirror_permissions" "11-directories_permissions" "12-directory_permissions" "13-change_group")
advanced=("100-change_owner_and_group" "101-symbolic_link_permissions" "102-if_only" "103-Star_Wars")

redirection=("0-hello_world"
       "1-confused_smiley"
"2-hellofile"
"3-twofiles"
"4-lastlines"
"5-firstlines"
"6-third_line"
"7-file"
"8-cwd_state"
"9-duplicate_last_line"
"10-no_more_js"
"11-directories"
"12-newest_files"
"13-unique"
"14-findthatword"
"15-countthatword"
"16-whatsnext"
"17-hidethisword"
"18-letteronly"
"19-AZ"
"20-hiago"
"21-reverse"
"22-users_and_homes")


variables=("0-alias"
	"1-hello_you"
"2-path"
"3-paths"
"4-global_variables"
"5-local_variables"
"6-create_local_variable"
"7-create_global_variable"
"8-true_knowledge"
"9-divide_and_rule"
"10-love_exponent_breath"
"11-binary_to_decimal"
"12-combinations"
"13-print_float")

for dest in "${variables[@]}"; do
  cp "$source_file" "$dest"
done
