#!/bin/bash

source_file="a"
destinations=("2-groups" "3-new_owner" "4-empty" "5-execute" "6-multiple_permissions" "7-everybody" "8-James_Bond" "9-John_Doe" "10-mirror_permissions" "11-directories_permissions" "12-directory_permissions" "13-change_group")

for dest in "${destinations[@]}"; do
  cp "$source_file" "$dest"
done
